baseURL = "/"
languageCode = "en-us"
title = "Dana Harrigan"
uglyurls = false
timeout = 120000
disableKinds = ['taxonomy', 'term']


[menu]
	[[menu.main]]
		name = "About Me"
		weight = 300
		url = "/info/about/"
		identifier = "about"

